# -*- coding: utf-8 -*-
"""mavevsfemaleusingcnnp7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XWVxVi1AtX5lg_JeX7bXIIyPURrKeg5V
"""

!pip install streamlit
import streamlit as st
import tensorflow as tf
import numpy as np
from PIL import Image

st.set_page_config(
    page_title="Face Gender Classification",
    page_icon="🧑",
    layout="wide"
)

# ----------------------------
# Load Model
# ----------------------------
@st.cache_resource
def load_model():
    model = tf.keras.models.load_model("my_model.keras")
    return model

model = load_model()

IMG_SIZE = (150, 150)

# ----------------------------
# Header
# ----------------------------
st.title("🧑 Face Gender Classification")
st.write("Upload a face image to predict whether the person is Male or Female using a CNN model.")

st.divider()

col1, col2 = st.columns(2)

with col1:
    st.info("""
### 👩 Student Details

**Name:** Aditi Srivastava

**Roll No:** 2401221550005

**Course:** B.Tech CSE (IoT)
""")

with col2:
    st.success("""
### 📌 Project Details

- CNN Based Gender Classification
- TensorFlow / Keras
- Streamlit Deployment
""")

st.divider()

uploaded_file = st.file_uploader(
    "Upload an Image",
    type=["jpg", "jpeg", "png"]
)
if uploaded_file is not None:

    image = Image.open(uploaded_file).convert("RGB")

    col1, col2 = st.columns(2)

    with col1:
        st.image(
            image,
            caption="Uploaded Face Image",
            use_container_width=True
        )

    # ----------------------------
    # Image Preprocessing
    # ----------------------------
    img = image.resize(IMG_SIZE)
    img = np.array(img)
    img = img.astype("float32") / 255.0
    img = np.expand_dims(img, axis=0)

    # ----------------------------
    # Prediction
    # ----------------------------
    with st.spinner("Predicting..."):
        prediction = model.predict(img, verbose=0)

    probability = float(prediction[0][0])

    # Debug (Remove later if desired)
    st.write("Raw Prediction :", probability)

    # Female = 0
    # Male = 1
    if probability >= 0.5:
        result = "Male"
        confidence = probability * 100
    else:
        result = "Female"
        confidence = (1 - probability) * 100
            # ----------------------------
    # Display Prediction
    # ----------------------------
    with col2:

        st.subheader("Prediction Result")

        if result == "Male":
            st.success(f"👨 Gender : {result}")
        else:
            st.info(f"👩 Gender : {result}")

        st.metric("Confidence", f"{confidence:.2f}%")

        st.progress(int(confidence))

        st.write("### Prediction Scores")
        st.write(f"**Male :** {probability * 100:.2f}%")
        st.write(f"**Female :** {(1 - probability) * 100:.2f}%")

else:
    st.warning("⚠️ Please upload a JPG, JPEG or PNG image.")

# ----------------------------
# Sidebar
# ----------------------------
st.sidebar.title("Model Information")

st.sidebar.write("""
### CNN Details

- **Algorithm:** Convolutional Neural Network (CNN)
- **Framework:** TensorFlow / Keras
- **Input Size:** 150 × 150
- **Output:** Binary Classification
- **Classes:** Male / Female
""")

st.sidebar.success("✅ Model Loaded Successfully")

# ----------------------------
# Footer
# ----------------------------
st.divider()

st.caption(
    "Developed by Aditi Srivastava | B.Tech CSE (IoT) | SRMCEM"
)